### ISSUE TITLE
Upgrading snipeit fails with "Error: failed to parse values.yaml"

### ISSUE THREAD

**Issue by nicja** [t3n/helm-charts#171]
I sucessfully installed this some months ago with muc hthe same .yaml. I am now trying to make some changes but am receving the following errors:

Error: failed to parse values.yaml: error converting YAML to JSON: yaml: line 85: did not find expected ',' or '}'
Error: failed to parse values.yaml: error converting YAML to JSON: yaml: line 93: did not find expected node content

I believe this is being caused by the ingress definition in values.yaml, but this was just copied and pasted from the default values.yaml with a few tweaks:
```
ingress:
  enabled: true
  annotations: {
    acme.cert-manager.io/http01-edit-in-place: "true"   # line 85
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /*
  hosts:
    - assets.masterst.art
  tls: [                                                            #line 93
    - secretName: tls-snipeit
      hosts:
        - assets.masterst.art
  ]
```

Any help is appreciated
