### ISSUE TITLE
Can not setup Snipe-IT - 500 SERVER ERROR

### ISSUE THREAD

**Issue by rhizoet** [t3n/helm-charts#194]
We have installed Snipe-IT on our K8s cluster 1.26.6. We have activated the internal MySQL for this.

At the beginning, MySQL states that a login with `root` is not possible (because of the password). After a short time, however, this status recovers. However, I doubt that this is how it should be.

When everything works, you call the URL and click on `Next: Create Databse Tables`, it takes a very long time, the snipeit pod is restarted (which is why the connection is briefly interrupted) and then you get a `500 | SERVER ERROR`.

What are we doing wrong? Our config looks like this:

```YAML
config:
  snipeit:
    url: https://asset.internal.regio.digital
    key: "base64:xxxx"

mysql:
  enabled: true

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - asset.example.com
  tls:
    - secretName: snipeit-internal-tls
      hosts:
        - asset.example.com
```

And this is what the web UI looks like at the beginning:

![snipe-it-issue](https://github.com/t3n/helm-charts/assets/58997736/0a747d31-ee11-4f37-9e3e-a2b4d3baa2b5)
