### ISSUE TITLE
Migration failed: { SequelizeConnectionError: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by piiot** [t3n/helm-charts#83]
```
root@tho-kub04:~# kubectl logs unms-746fdc98d9-zmwtn -n unms
Running docker-entrypoint yarn start
Running UNMS container as root
Creating service user app (uid=1000)
Creating directories and setting permissions
creating /home/app/unms/supportinfo
setting permissions on /home/app/unms/supportinfo
creating /home/app/unms/data/cert
setting permissions on /home/app/unms/data/cert
creating /home/app/unms/data/images
setting permissions on /home/app/unms/data/images
creating /home/app/unms/data/firmwares
setting permissions on /home/app/unms/data/firmwares
creating /home/app/unms/data/logs
setting permissions on /home/app/unms/data/logs
creating /home/app/unms/data/config-backups
setting permissions on /home/app/unms/data/config-backups
creating /home/app/unms/data/unms-backups
setting permissions on /home/app/unms/data/unms-backups
creating /home/app/unms/data/import
setting permissions on /home/app/unms/data/import
creating /home/app/unms/data/update
setting permissions on /home/app/unms/data/update
Linking /home/app/unms/public/site-images -> /home/app/unms/data/images
Linking /home/app/unms/public/firmwares -> /home/app/unms/data/firmwares
Stepping down from root: su-exec "/usr/local/bin/docker-entrypoint.sh" "yarn start"
Running docker-entrypoint yarn start
Waiting for database containers
psql: fe_sendauth: no password supplied
Background append only file rewriting started
Exec yarn start
yarn run v1.9.4
warning Skipping preferred cache folder "/home/app/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
$ npm run backup:apply && npm run migrate && node --max_old_space_size=2048 index.js
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/app/.yarn"

> unms-server@0.13.3 backup:apply /home/app/unms
> node ./cli/apply-backup

UNMS BACKUP start
There is no UNMS backup found
UNMS BACKUP finished

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/app/.config │
└───────────────────────────────────────────────────────┘

> unms-server@0.13.3 migrate /home/app/unms
> node ./cli/migrate.js

Migration failed: { SequelizeConnectionError: password authentication failed for user "postgres"
    at /home/app/unms/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:110:20
    at Connection.<anonymous> (/home/app/unms/node_modules/pg/lib/client.js:185:5)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/home/app/unms/node_modules/pg/lib/connection.js:121:12)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
  name: 'SequelizeConnectionError',
  message: 'password authentication failed for user "postgres"',
  parent:
   { error: password authentication failed for user "postgres"
       at Connection.parseE (/home/app/unms/node_modules/pg/lib/connection.js:554:11)
       at Connection.parseMessage (/home/app/unms/node_modules/pg/lib/connection.js:381:17)
       at Socket.<anonymous> (/home/app/unms/node_modules/pg/lib/connection.js:117:22)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onread (net.js:639:20)
     name: 'error',
     length: 104,
     severity: 'FATAL',
     code: '28P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'auth.c',
     line: '337',
     routine: 'auth_failed' },
  original:
   { error: password authentication failed for user "postgres"
       at Connection.parseE (/home/app/unms/node_modules/pg/lib/connection.js:554:11)
       at Connection.parseMessage (/home/app/unms/node_modules/pg/lib/connection.js:381:17)
       at Socket.<anonymous> (/home/app/unms/node_modules/pg/lib/connection.js:117:22)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onread (net.js:639:20)
     name: 'error',
     length: 104,
     severity: 'FATAL',
     code: '28P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'auth.c',
     line: '337',
     routine: 'auth_failed' } }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unms-server@0.13.3 migrate: `node ./cli/migrate.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unms-server@0.13.3 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not exactly sure what I'm missing here.  I haven't done any modifications to your values.yaml other than adding a few modifications to PVC's.

```
root@tho-kub04:~# kubectl get pods -n unms
NAME                          READY   STATUS    RESTARTS   AGE
unms-746fdc98d9-zmwtn         0/1     Error     5          3m52s
unms-nginx-7666565dc9-dg9wx   1/1     Running   0          14m
unms-postgresql-0             1/1     Running   0          3m39s
unms-rabbitmq-ha-0            1/1     Running   0          67m
unms-rabbitmq-ha-1            1/1     Running   0          68m
unms-rabbitmq-ha-2            1/1     Running   0          67m
unms-redis-master-0           1/1     Running   0          68m
```

values.yaml:
```
replicaCount: 1
revisionHistoryLimit: 0

## PodDisruptionBudget
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
# maxUnavailable: 1

image:
  repository: ubnt/unms
  tag: 0.13.3
  pullPolicy: IfNotPresent

  nginx:
    repository: ubnt/unms-nginx
    tag: 0.13.3
    pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  annotations: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - unms.internal.example.com
  #tls:
  #  - secretName: unms-tls
  #    hosts:
  #      - example.local

# Leave default to use rabbitmq of this chart
rabbitmq-ha:
  host: unms-rabbitmq-ha
  port: "5672"
  rabbitmqUsername: guest
  rabbitmqPassword: guest
  rabbitmqAuth:
    enabled: true
    config: |
      auth_mechanisms.1 = PLAIN
      auth_mechanisms.2 = AMQPLAIN
  persistence:
    enabled: true
    persistence:
      storageClassName: "managed-nfs-storage"
      accessMode: ReadWriteOnce
      size: 5Gi
  prometheus:
    operator:
      enabled: false

# Leave default to use redis of this chart
redis:
  host: unms-redis-master
  port: "6379"
  cluster:
    enabled: false
  usePassword: false
  master:
    persistence:
      enabled: true
      storageClass: "managed-nfs-storage"
      accessMode: ReadWriteOnce
      size: 5Gi


# Leave default to use postgresql of this chart
postgresql:
  host: unms-postgresql
  port: "5432"
  postgresPassword: Password123@
  postgresDatabase: unms
  persistence:
    storageClass: "managed-nfs-storage"
    accessMode: ReadWriteOnce
    size: 5Gi
    resourcePolicy: nil

persistence:
  enabled: true
  annotations: {}
  accessMode: ReadWriteOnce
  existingClaim: ""
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClassName: "managed-nfs-storage"
  size: 5Gi

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi

mysql-backup:
  enabled: false
```
