### ISSUE TITLE
Snipeit: Readiness/Liveness probe failed: Get http://10.33.135.142:80/login: dial tcp 10.33.135.142:80: connect: connection refused

### ISSUE THREAD

**Issue by manisha-tanwar** [t3n/helm-charts#91]
Hi Team,

I cloned latest version of snipeit chart and modified values.yaml as below:

```
image:
  repository: snipe/snipe-it
  tag: v4.9.4
  pullPolicy: IfNotPresent

service:
  type: NodePort
  http:
    port: 80
  https:
    port: 443

config:
  snipeit:
    env: production
    debug: true
    url: https://myurl.local
    key: "base64:MU48gIU3bWN7z0Z1U/SXYUIiZSJxp3MuHxNPPS4haW4="
    timezone: Etc/GMT
    locale: en_GB

mysql:
  enabled: true
  mysqlUser: snipeit
  mysqlPassword: "snipeit"
  mysqlDatabase: db-snipeit

  persistence:
    enabled: false
persistence:
  enabled: false
mysql-backup:
  enabled: false

ingress:
  enabled: true
  annotations:
    <Own annotations>
  path: /
  hosts:
    - myurl.local
  tls:
    - secretName: snipeit-tls-secret
      hosts:
        - myurl.local
```

But after doing helm install, pod doesn't come up and gives below errors:

> 25m         Warning   Unhealthy           pod/snipeit-gb4-65486dfd78-25zk9                         Readiness probe failed: Get http://10.33.135.142:80/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
25m         Warning   Unhealthy           pod/snipeit-gb4-65486dfd78-25zk9                         Readiness probe failed: Get http://10.33.135.142:80/login: dial tcp 10.33.135.142:80: connect: connection refused
25m         Warning   Unhealthy           pod/snipeit-gb4-65486dfd78-25zk9                         Liveness probe failed: Get http://10.33.135.142:80/login: dial tcp 10.33.135.142:80: connect: connection refused

Also got below error for pod:
>Module ssl disabled.
To activate the new configuration, you need to run:
  service apache2 restart
2020-09-01 22:11:56,294 CRIT Supervisor running as root (no user in config file)
2020-09-01 22:11:56,297 INFO supervisord started with pid 1
2020-09-01 22:11:57,300 INFO spawned: 'exit_on_any_fatal' with pid 21
2020-09-01 22:11:57,302 INFO spawned: 'apache' with pid 22
2020-09-01 22:11:57,388 INFO spawned: 'run_schedule' with pid 23
2020-09-01 22:11:58,488 INFO success: exit_on_any_fatal entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-09-01 22:11:58,488 INFO success: apache entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-09-01 22:11:58,488 INFO success: run_schedule entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.33.135.18. Set the 'ServerName' directive globally to suppress this message
No scheduled commands are ready to run.

I'm not able to understand why supervisor is killing the process.

Also I'd like to know is config.snipeit.url is same as ingress.hosts? Please help!

**Comment by manisha-tanwar** [comment]
after changing few things in readiness/liveness I don't see same error anymore but pod is getting CrashLoopBackOff & start again every now & then.
When pod is Running I tried to hit my ingress URL which gave me all the details on webpage itself like env var 

> Illuminate \ Database \ QueryException (2002)
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = db-snipeit and table_name = users)
Previous exceptions
SQLSTATE[HY000] [2002] Connection refused (2002)
SQLSTATE[HY000] [2002] Connection refused (2002)

**Comment by mschmidt291** [comment]
That's more of a configuration issue. Did you specify your mysql-host in the values.yaml? This entry is missing in your posted values.yaml.

**Comment by manisha-tanwar** [comment]
Thanks for replying @mschmidt291 
I didn't set external mysql so these values are defaults:
```
config:
  mysql:
  ## All of these values are only used when mysql.enabled is set to false
    externalDatabase:
      user: "snipeit"
      pass: ""
      name: db-snipeit
      host: mysql
      port: 3306
mysql:
  ## Whether to deploy a mysql server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Create a database and a database user
  ##
  mysqlUser: snipeit
  mysqlPassword: "snipeit"
  mysqlDatabase: db-snipeit

  persistence:
    enabled: false
      ## mysql data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi
```

Do I need to provide host even if I want it to create? I don't know the pod IP, should I just mention localhost/127.0.0.1. In secret.yaml I see it as:
`  MYSQL_PORT_3306_TCP_ADDR: {{ include "snipeit.mysqlFullname" . | b64enc }}`

which is coming from _helpers.tpl as
```
{{- define "snipeit.mysqlFullname" -}}
{{- $mysqlContext := dict "Values" .Values.mysql "Release" .Release "Chart" (dict "Name" "mysql") -}}
{{ template "snipeit.fullname" $mysqlContext }}
{{- end -}}
```
I've changed line from `{{ template "mysql.fullname" $mysqlContext }}` to `{{ template "snipeit.fullname" $mysqlContext }}` 
as I got below error when cloned and run it as it is:

> [debug] SERVER: "127.0.0.1:44134"
> UPGRADE FAILED
> Error: render error in "snipeit/templates/secret.yaml": template: snipeit/templates/secret.yaml:12:31: executing "snipeit/templates/secret.yaml" at <include "snipeit.mysqlFullname" .>: error calling include: template: snipeit/templates/_helpers.tpl:39:12: executing "snipeit.mysqlFullname" at <{{template "mysql.fullname" $mysqlContext}}>: template "mysql.fullname" not defined
> Error: UPGRADE FAILED: render error in "snipeit/templates/secret.yaml": template: snipeit/templates/secret.yaml:12:31: executing "snipeit/templates/secret.yaml" at <include "snipeit.mysqlFullname" .>: error calling include: template: snipeit/templates/_helpers.tpl:39:12: executing "snipeit.mysqlFullname" at <{{template "mysql.fullname" $mysqlContext}}>: template "mysql.fullname" not defined
> upon checking _helpers.tpl it seems like mysql.fullname isn't defined.
